### ISSUE TITLE
qt6gtk2 doesn't work with Qt 6.6

### ISSUE THREAD

**Issue by guiodic** [trialuser02/qt6gtk2#11]
On Arch with QT 6.6, qt6gtk2 doesnt work and QT falls back to "windows 95" theme.

**Comment by trialuser02** [comment]
Try to recompile it.

**Comment by guiodic** [comment]
That was the first thing I did, but it didn't work.

**Comment by guiodic** [comment]
`$ QT_QPA_PLATFORMTHEME=gtk2 QT_DEBUG_PLUGINS=1 QT_LOGGING_RULES=plugins=true qt6ct

qt.core.plugin.factoryloader: checking directory path "/usr/lib/qt6/plugins/platforms" ...
qt.core.plugin.factoryloader: looking at "/usr/lib/qt6/plugins/platforms/libqeglfs.so"
qt.core.plugin.loader: Found metadata in lib /usr/lib/qt6/plugins/platforms/libqeglfs.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "eglfs"
        ]
    },
    "archlevel": 1,
    "className": "QEglFSIntegrationPlugin",
    "debug": false,
    "version": 394752
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("eglfs")
qt.core.plugin.factoryloader: looking at "/usr/lib/qt6/plugins/platforms/libqlinuxfb.so"
qt.core.plugin.loader: Found metadata in lib /usr/lib/qt6/plugins/platforms/libqlinuxfb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "linuxfb"
        ]
    },
    "archlevel": 1,
    "className": "QLinuxFbIntegrationPlugin",
    "debug": false,
    "version": 394752
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("linuxfb")
qt.core.plugin.factoryloader: looking at "/usr/lib/qt6/plugins/platforms/libqminimal.so"
qt.core.plugin.loader: Found metadata in lib /usr/lib/qt6/plugins/platforms/libqminimal.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimal"
        ]
    },
    "archlevel": 1,
    "className": "QMinimalIntegrationPlugin",
    "debug": false,
    "version": 394752
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("minimal")
qt.core.plugin.factoryloader: looking at "/usr/lib/qt6/plugins/platforms/libqminimalegl.so"
qt.core.plugin.loader: Found metadata in lib /usr/lib/qt6/plugins/platforms/libqminimalegl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimalegl"
        ]
    },
    "archlevel": 1,
    "className": "QMinimalEglIntegrationPlugin",
    "debug": false,
    "version": 394752
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("minimalegl")
qt.core.plugin.factoryloader: looking at "/usr/lib/qt6/plugins/platforms/libqoffscreen.so"
qt.core.plugin.loader: Found metadata in lib /usr/lib/qt6/plugins/platforms/libqoffscreen.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "offscreen"
        ]
    },
    "archlevel": 1,
    "className": "QOffscreenIntegrationPlugin",
    "debug": false,
    "version": 394752
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("offscreen")
qt.core.plugin.factoryloader: looking at "/usr/lib/qt6/plugins/platforms/libqvkkhrdisplay.so"
qt.core.plugin.loader: Found metadata in lib /usr/lib/qt6/plugins/platforms/libqvkkhrdisplay.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "vkkhrdisplay"
        ]
    },
    "archlevel": 1,
    "className": "QVkKhrDisplayIntegrationPlugin",
    "debug": false,
    "version": 394752
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("vkkhrdisplay")
qt.core.plugin.factoryloader: looking at "/usr/lib/qt6/plugins/platforms/libqvnc.so"
qt.core.plugin.loader: Found metadata in lib /usr/lib/qt6/plugins/platforms/libqvnc.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "vnc"
        ]
    },
    "archlevel": 1,
    "className": "QVncIntegrationPlugin",
    "debug": false,
    "version": 394752
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("vnc")
qt.core.plugin.factoryloader: looking at "/usr/lib/qt6/plugins/platforms/libqxcb.so"
qt.core.plugin.loader: Found metadata in lib /usr/lib/qt6/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "archlevel": 1,
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 394752
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("xcb")
qt.core.plugin.factoryloader: checking directory path "/usr/bin/platforms" ...
qt.core.library: "/usr/lib/qt6/plugins/platforms/libqxcb.so" loaded library
qt.core.plugin.factoryloader: checking directory path "/usr/lib/qt6/plugins/platformthemes" ...
qt.core.plugin.factoryloader: looking at "/usr/lib/qt6/plugins/platformthemes/libqgtk3.so"
qt.core.plugin.loader: Found metadata in lib /usr/lib/qt6/plugins/platformthemes/libqgtk3.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformThemeFactoryInterface.5.1",
    "MetaData": {
        "Keys": [
            "gtk3"
        ]
    },
    "archlevel": 1,
    "className": "QGtk3ThemePlugin",
    "debug": false,
    "version": 394752
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("gtk3")
qt.core.plugin.factoryloader: looking at "/usr/lib/qt6/plugins/platformthemes/libqxdgdesktopportal.so"
qt.core.plugin.loader: Found metadata in lib /usr/lib/qt6/plugins/platformthemes/libqxdgdesktopportal.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformThemeFactoryInterface.5.1",
    "MetaData": {
        "Keys": [
            "xdgdesktopportal",
            "flatpak",
            "snap"
        ]
    },
    "archlevel": 1,
    "className": "QXdgDesktopPortalThemePlugin",
    "debug": false,
    "version": 394752
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("xdgdesktopportal", "flatpak", "snap")
qt.core.plugin.factoryloader: looking at "/usr/lib/qt6/plugins/platformthemes/libqt6ct.so"
qt.core.plugin.loader: Found metadata in lib /usr/lib/qt6/plugins/platformthemes/libqt6ct.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformThemeFactoryInterface.5.1",
    "MetaData": {
        "Keys": [
            "qt6ct",
            "qt5ct"
        ]
    },
    "archlevel": 1,
    "className": "Qt6CTPlatformThemePlugin",
    "debug": false,
    "version": 394752
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("qt6ct", "qt5ct")
qt.core.plugin.factoryloader: looking at "/usr/lib/qt6/plugins/platformthemes/libqt6gtk2.so"
qt.core.plugin.loader: Found metadata in lib /usr/lib/qt6/plugins/platformthemes/libqt6gtk2.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformThemeFactoryInterface.5.1",
    "MetaData": {
        "Keys": [
            "gtk2",
            "qt6gtk2",
            "qt5gtk2"
        ]
    },
    "archlevel": 1,
    "className": "Qt6Gtk2ThemePlugin",
    "debug": false,
    "version": 394752
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("gtk2", "qt6gtk2", "qt5gtk2")
qt.core.plugin.factoryloader: checking directory path "/usr/bin/platformthemes" ...
qt.core.library: "/usr/lib/qt6/plugins/platformthemes/libqt6gtk2.so" loaded library
qt.core.plugin.factoryloader: checking directory path "/usr/lib/qt6/plugins/platforminputcontexts" ...
qt.core.plugin.factoryloader: looking at "/usr/lib/qt6/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so"
qt.core.plugin.loader: Found metadata in lib /usr/lib/qt6/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so, metadata=
{
    "IID": "org.qt-project.Qt.QPlatformInputContextFactoryInterface.5.1",
    "MetaData": {
        "Keys": [
            "compose",
            "xim"
        ]
    },
    "archlevel": 1,
    "className": "QComposePlatformInputContextPlugin",
    "debug": false,
    "version": 394752
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("compose", "xim")
qt.core.plugin.factoryloader: looking at "/usr/lib/qt6/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so"
qt.core.plugin.loader: Found metadata in lib /usr/lib/qt6/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so, metadata=
{
    "IID": "org.qt-project.Qt.QPlatformInputContextFactoryInterface.5.1",
    "MetaData": {
        "Keys": [
            "ibus"
        ]
    },
    "archlevel": 1,
    "className": "QIbusPlatformInputContextPlugin",
    "debug": false,
    "version": 394752
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("ibus")
qt.core.plugin.factoryloader: checking directory path "/usr/bin/platforminputcontexts" ...
qt.core.library: "/usr/lib/qt6/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so" loaded library
qt.core.plugin.factoryloader: checking directory path "/usr/lib/qt6/plugins/styles" ...
qt.core.plugin.factoryloader: looking at "/usr/lib/qt6/plugins/styles/libqt6ct-style.so"
qt.core.plugin.loader: Found metadata in lib /usr/lib/qt6/plugins/styles/libqt6ct-style.so, metadata=
{
    "IID": "org.qt-project.Qt.QStyleFactoryInterface",
    "MetaData": {
        "Keys": [
            "qt6ct-style",
            "qt5ct-style"
        ]
    },
    "archlevel": 1,
    "className": "Qt6CTStylePlugin",
    "debug": false,
    "version": 394752
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("qt6ct-style", "qt5ct-style")
qt.core.plugin.factoryloader: looking at "/usr/lib/qt6/plugins/styles/libqt6gtk2-style.so"
qt.core.plugin.loader: Found metadata in lib /usr/lib/qt6/plugins/styles/libqt6gtk2-style.so, metadata=
{
    "IID": "org.qt-project.Qt.QStyleFactoryInterface",
    "MetaData": {
        "Keys": [
            "gtk2",
            "qt6gtk2",
            "qt5gtk2"
        ]
    },
    "archlevel": 1,
    "className": "Qt6Gtk2StylePlugin",
    "debug": false,
    "version": 394752
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("gtk2", "qt6gtk2", "qt5gtk2")
qt.core.plugin.factoryloader: looking at "/usr/lib/qt6/plugins/styles/oodwaita.so"
qt.core.plugin.loader: Found metadata in lib /usr/lib/qt6/plugins/styles/oodwaita.so, metadata=
{
    "IID": "org.qt-project.Qt.QStyleFactoryInterface",
    "MetaData": {
        "Keys": [
            "Oomox"
        ]
    },
    "archlevel": 1,
    "className": "StylePlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("oomox")
qt.core.plugin.factoryloader: looking at "/usr/lib/qt6/plugins/styles/breeze6.so"
qt.core.plugin.loader: Found metadata in lib /usr/lib/qt6/plugins/styles/breeze6.so, metadata=
{
    "IID": "org.qt-project.Qt.QStyleFactoryInterface",
    "MetaData": {
        "Keys": [
            "Breeze"
        ]
    },
    "archlevel": 1,
    "className": "StylePlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("breeze")
qt.core.plugin.factoryloader: checking directory path "/usr/bin/styles" ...
qt.core.library: "/usr/lib/qt6/plugins/styles/libqt6gtk2-style.so" loaded library
QGuiApplication::setDesktopFileName: the specified desktop file name ends with .desktop. For compatibility reasons, the .desktop suffix will be removed. Please specify a desktop file name without .desktop suffix
Configuration path: "/home/guido/.config/qt6ct"
Shared QSS paths: QList("/home/guido/.local/share/qt6ct/qss", "/usr/local/share/qt6ct/qss", "/usr/share/qt6ct/qss")
Shared color scheme paths: QList("/home/guido/.local/share/qt6ct/colors", "/usr/local/share/qt6ct/colors", "/usr/share/qt6ct/colors")
qt.core.plugin.factoryloader: checking directory path "/usr/lib/qt6/plugins/iconengines" ...
qt.core.plugin.factoryloader: looking at "/usr/lib/qt6/plugins/iconengines/libqsvgicon.so"
qt.core.plugin.loader: Found metadata in lib /usr/lib/qt6/plugins/iconengines/libqsvgicon.so, metadata=
{
    "IID": "org.qt-project.Qt.QIconEngineFactoryInterface",
    "MetaData": {
        "Keys": [
            "svg",
            "svgz",
            "svg.gz"
        ]
    },
    "archlevel": 1,
    "className": "QSvgIconPlugin",
    "debug": false,
    "version": 394752
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("svg", "svgz", "svg.gz")
qt.core.plugin.factoryloader: checking directory path "/usr/bin/iconengines" ...
qt.core.plugin.factoryloader: checking directory path "/usr/lib/qt6/plugins/imageformats" ...
qt.core.plugin.factoryloader: looking at "/usr/lib/qt6/plugins/imageformats/libqgif.so"
qt.core.plugin.loader: Found metadata in lib /usr/lib/qt6/plugins/imageformats/libqgif.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "gif"
        ],
        "MimeTypes": [
            "image/gif"
        ]
    },
    "archlevel": 1,
    "className": "QGifPlugin",
    "debug": false,
    "version": 394752
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("gif")
qt.core.plugin.factoryloader: looking at "/usr/lib/qt6/plugins/imageformats/libqico.so"
qt.core.plugin.loader: Found metadata in lib /usr/lib/qt6/plugins/imageformats/libqico.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "ico",
            "cur"
        ],
        "MimeTypes": [
            "image/vnd.microsoft.icon",
            "image/vnd.microsoft.icon"
        ]
    },
    "archlevel": 1,
    "className": "QICOPlugin",
    "debug": false,
    "version": 394752
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("ico", "cur")
qt.core.plugin.factoryloader: looking at "/usr/lib/qt6/plugins/imageformats/libqjpeg.so"
qt.core.plugin.loader: Found metadata in lib /usr/lib/qt6/plugins/imageformats/libqjpeg.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "jpg",
            "jpeg"
        ],
        "MimeTypes": [
            "image/jpeg",
            "image/jpeg"
        ]
    },
    "archlevel": 1,
    "className": "QJpegPlugin",
    "debug": false,
    "version": 394752
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("jpg", "jpeg")
qt.core.plugin.factoryloader: looking at "/usr/lib/qt6/plugins/imageformats/libqsvg.so"
qt.core.plugin.loader: Found metadata in lib /usr/lib/qt6/plugins/imageformats/libqsvg.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "svg",
            "svgz"
        ],
        "MimeTypes": [
            "image/svg+xml",
            "image/svg+xml-compressed"
        ]
    },
    "archlevel": 1,
    "className": "QSvgPlugin",
    "debug": false,
    "version": 394752
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("svg", "svgz")
qt.core.plugin.factoryloader: looking at "/usr/lib/qt6/plugins/imageformats/libqicns.so"
qt.core.plugin.loader: Found metadata in lib /usr/lib/qt6/plugins/imageformats/libqicns.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "icns"
        ],
        "MimeTypes": [
            "image/x-icns"
        ]
    },
    "archlevel": 1,
    "className": "QICNSPlugin",
    "debug": false,
    "version": 394752
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("icns")
qt.core.plugin.factoryloader: looking at "/usr/lib/qt6/plugins/imageformats/libqjp2.so"
qt.core.plugin.loader: Found metadata in lib /usr/lib/qt6/plugins/imageformats/libqjp2.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "jp2"
        ],
        "MimeTypes": [
            "image/jp2",
            "image/jpx",
            "image/jpm",
            "video/mj2"
        ]
    },
    "archlevel": 1,
    "className": "QJp2Plugin",
    "debug": false,
    "version": 394752
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("jp2")
qt.core.plugin.factoryloader: looking at "/usr/lib/qt6/plugins/imageformats/libqmng.so"
qt.core.plugin.loader: Found metadata in lib /usr/lib/qt6/plugins/imageformats/libqmng.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "mng"
        ],
        "MimeTypes": [
            "image/x-mng"
        ]
    },
    "archlevel": 1,
    "className": "QMngPlugin",
    "debug": false,
    "version": 394752
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("mng")
qt.core.plugin.factoryloader: looking at "/usr/lib/qt6/plugins/imageformats/libqtga.so"
qt.core.plugin.loader: Found metadata in lib /usr/lib/qt6/plugins/imageformats/libqtga.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "tga"
        ],
        "MimeTypes": [
            "image/x-tga"
        ]
    },
    "archlevel": 1,
    "className": "QTgaPlugin",
    "debug": false,
    "version": 394752
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("tga")
qt.core.plugin.factoryloader: looking at "/usr/lib/qt6/plugins/imageformats/libqtiff.so"
qt.core.plugin.loader: Found metadata in lib /usr/lib/qt6/plugins/imageformats/libqtiff.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "tiff",
            "tif"
        ],
        "MimeTypes": [
            "image/tiff",
            "image/tiff"
        ]
    },
    "archlevel": 1,
    "className": "QTiffPlugin",
    "debug": false,
    "version": 394752
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("tiff", "tif")
qt.core.plugin.factoryloader: looking at "/usr/lib/qt6/plugins/imageformats/libqwbmp.so"
qt.core.plugin.loader: Found metadata in lib /usr/lib/qt6/plugins/imageformats/libqwbmp.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "wbmp"
        ],
        "MimeTypes": [
            "image/vnd.wap.wbmp"
        ]
    },
    "archlevel": 1,
    "className": "QWbmpPlugin",
    "debug": false,
    "version": 394752
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("wbmp")
qt.core.plugin.factoryloader: looking at "/usr/lib/qt6/plugins/imageformats/libqwebp.so"
qt.core.plugin.loader: Found metadata in lib /usr/lib/qt6/plugins/imageformats/libqwebp.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "webp"
        ],
        "MimeTypes": [
            "image/webp"
        ]
    },
    "archlevel": 1,
    "className": "QWebpPlugin",
    "debug": false,
    "version": 394752
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("webp")
qt.core.plugin.factoryloader: checking directory path "/usr/bin/imageformats" ...
qt.core.library: "/usr/lib/qt6/plugins/imageformats/libqgif.so" loaded library
qt.core.library: "/usr/lib/qt6/plugins/imageformats/libqico.so" loaded library
qt.core.library: "/usr/lib/qt6/plugins/imageformats/libqjpeg.so" loaded library
qt.core.library: "/usr/lib/qt6/plugins/imageformats/libqsvg.so" loaded library
qt.core.library: "/usr/lib/qt6/plugins/imageformats/libqicns.so" loaded library
qt.core.library: "/usr/lib/qt6/plugins/imageformats/libqjp2.so" loaded library
qt.core.library: "/usr/lib/qt6/plugins/imageformats/libqmng.so" loaded library
qt.core.library: "/usr/lib/qt6/plugins/imageformats/libqtga.so" loaded library
qt.core.library: "/usr/lib/qt6/plugins/imageformats/libqtiff.so" loaded library
qt.core.library: "/usr/lib/qt6/plugins/imageformats/libqwbmp.so" loaded library
qt.core.library: "/usr/lib/qt6/plugins/imageformats/libqwebp.so" loaded library
qt.core.library: "/usr/lib/qt6/plugins/iconengines/libqsvgicon.so" loaded library
qt.core.plugin.factoryloader: checking directory path "/usr/lib/qt6/plugins/accessible" ...
qt.core.plugin.factoryloader: checking directory path "/usr/bin/accessible" ...
qt.core.plugin.factoryloader: checking directory path "/usr/lib/qt6/plugins/accessiblebridge" ...
qt.core.plugin.factoryloader: checking directory path "/usr/bin/accessiblebridge" ...`

**Comment by trialuser02** [comment]
QT_STYLE_OVERRIDE?

**Comment by guiodic** [comment]
QT_QPA_PLATFORMTHEME=gtk2 QT_STYLE_OVERRIDE=gtk2  qt6ct

same result...

**Comment by trialuser02** [comment]
Try to start /usr/lib/qt6/bin/assistant instead of qt6ct.

**Comment by guiodic** [comment]
Same result. Happens with all Qt6 apps, not a qt6ct problem.
