### ISSUE TITLE
Doesn't support Ubuntu; No DEB File

### ISSUE THREAD

**Issue by RichCat6** [trialuser02/qt6gtk2#7]
Can you potentially add support for Ubuntu? I need this for a qt6 application to respect my gtk2 system theme, and I'm running under Ubuntu 22.04. It'd be nice to have this work.

Thanks in advance.

**Comment by cobalt2727** [comment]
First off you'll need to install a few dependencies - I might be missing one or two, but this is everything I inferred from the README:
`sudo apt install qt6-base-dev qmake6 libgtk2.0-dev libx11-dev`

Then you can just build it yourself.
```bash
cd /tmp
git clone https://github.com/trialuser02/qt6gtk2
cd qt6gtk2
git pull
qmake6 .
make -j$(nproc)
sudo make install
```

**Comment by trialuser02** [comment]
Use packages from this ppa: https://launchpad.net/~forkotov02/+archive/ubuntu/extrappa

**Comment by cobalt2727** [comment]
...I had no idea that existed. Neat!

**Comment by cobalt2727** [comment]
> Use packages from this ppa: https://launchpad.net/~forkotov02/+archive/ubuntu/extrappa

Any chance you could extend this to more architectures/possibly even backport it using something like [this PPA](https://launchpad.net/~okirby/+archive/ubuntu/qt6-backports) as a dependency?
Enabling more architectures is as easy as checking some boxes in the PPA settings, but I understand if you don't want to go through the effort of setting up a backport.
