### ISSUE TITLE
Incompatible qt version

### ISSUE THREAD

**Issue by purpleleaf** [trialuser02/qt6gtk2#8]
on arch qt6gtk2 does not work.
launching qt6ct report this error:
"qt6gtk2 is compiled against incompatible Qt version (6.3.2)."

**Comment by trialuser02** [comment]
Recompile qt6gtk2 with your Qt version.

**Comment by purpleleaf** [comment]
Since the aur package is mentioned in the github homepage i was thinking the aur package mantainer could be involved in qt6gtk2 development......
i will report this problem on aur.
thanks, you can close this issue.
